USE [master]
GO

/****** Object:  Database [TimeData]    Script Date: 6/25/2024 3:05:20 PM ******/
CREATE DATABASE [TimeData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TimeData', FILENAME = N'C:\Users\nkommareddy\TimeData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TimeData_log', FILENAME = N'C:\Users\nkommareddy\TimeData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TimeData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TimeData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TimeData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TimeData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TimeData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TimeData] SET ARITHABORT OFF 
GO

ALTER DATABASE [TimeData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TimeData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TimeData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TimeData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TimeData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TimeData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TimeData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TimeData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TimeData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TimeData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TimeData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TimeData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TimeData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TimeData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TimeData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TimeData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TimeData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TimeData] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TimeData] SET  MULTI_USER 
GO

ALTER DATABASE [TimeData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TimeData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TimeData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TimeData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TimeData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TimeData] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TimeData] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TimeData] SET  READ_WRITE 
GO

